[default]

dirpath='originTemplate'

originTemplateDir='D:\\tools\\Export\\originTemplate'

originCodeTemplateDir='D:\\tools\\Export'

projectTemplateDir='E:\\template'
codeDir='E:\\Project'

reportNames=['变频最新监测数据.xlsx','电流图最新监测数据.xlsx','功率图最新监测数据.xlsx','功图监测最新数据.xlsx','配水间最新监测数据.xlsx','注水井最新监测数据.xlsx','电参最新监测数据.xlsx']

reportHistoryNames=['变频历史监测数据.xlsx','电流图历史监测数据.xlsx','功率图历史监测数据.xlsx','功图历史监测数据.xlsx','配水间历史监测数据.xlsx','注水井历史监测数据.xlsx','电参历史监测数据.xlsx']

templateNames=['FrequencyCheck.xlsx','CurrentDiagramCheck.xlsx','PowerDiagramCheck.xlsx','GDiagramCheck.xlsx','WaterStationCheck.xlsx','ZWellCheck.xlsx','PowerMetadiagram.xlsx']
templateHistoryNames=['FrequencyHistoryCheck.xlsx','CurrentDiagramHistoryCheck.xlsx','PowerDiagramHistoryCheck.xlsx','GDiagramHistoryCheck.xlsx','WaterStationHistoryCheck.xlsx','ZWellHistoryCheck.xlsx','PowerMetadiagramHistory.xlsx']

codeNames=['FrequencyCheck','CurrentDiagramCheck','PowerDiagramCheck','GDiagramCheck','WaterStationCheck','ZWellCheck','PowerMetadiagram']

DataSourceClassNames=['ViewIotDataOilwellControllerstateLatest','ViewIotDataOilwellCurrentdiagramLatest','ViewIotDataOilWellPowerDiagramLatest','ViewIotDataOilwellIndicatordiagramLatest','ViewIotDataWaterStationLatest','ViewWaterStationWaterWellLatest','ViewIotDataOilwellPowermeterLatest']
DataSourceClassHistoryNames=['ViewIotDataOilwellControllerstate','ViewIotDataOilwellCurrentdiagram','ViewIotDataOilWellPowerDiagram','ViewIotDataOilwellIndicatordiagram','ViewIotDataWaterStation','ViewWaterStationWaterWell','ViewIotDataOilwellPowermeter']




